export const STORES = ['Walmart', 'Kroger', 'Albertsons', "Sam's Club", 'Costco', 'Whole Foods']

export const DEFAULT_STORES = [
  { name: 'Walmart',      color: 'bg-blue-100 text-blue-800',    order: 1 },
  { name: 'Kroger',       color: 'bg-red-100 text-red-800',      order: 2 },
  { name: 'Albertsons',   color: 'bg-orange-100 text-orange-800',order: 3 },
  { name: "Sam's Club",   color: 'bg-indigo-100 text-indigo-800',order: 4 },
  { name: 'Costco',       color: 'bg-rose-100 text-rose-900',    order: 5 },
  { name: 'Whole Foods',  color: 'bg-green-100 text-green-800',  order: 6 },
]

export const CATEGORIES = [
  'Baby & Kids', 'Produce', 'Dairy & Eggs', 'Meat & Seafood', 'Pantry',
  'Seasonings & Spices', 'Bread & Bakery', 'Frozen', 'Beverages', 'Snacks',
  'Household', 'Health & Personal Care'
]

export const SEED_ITEMS = [
  // Walmart
  { name: "Goodnites S/M 44 count", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false },
  { name: "Goodnites L 11 count", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false },
  { name: "4 Gal Trash Bag", primaryStore: "Walmart", category: "Household", active: true, checked: false },
  { name: "Bandaids", primaryStore: "Walmart", category: "Health & Personal Care", active: true, checked: false },
  { name: "Richard's Roux", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Crackers", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Snacks", active: true, checked: false },
  { name: "Baking soda", primaryStore: "Walmart", category: "Pantry", active: true, checked: false },
  { name: "Garlic powder Seasoning (Organic)", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Organic Pears/peaches", primaryStore: "Walmart", category: "Produce", active: true, checked: false, notes: "if you see a bag, the greener the better; if yellow don't buy" },
  { name: "Organic Sweet potatoes", primaryStore: "Walmart", category: "Produce", active: true, checked: false },
  { name: "Green onion (Organic)", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Brussels Sprouts", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Avocado Organic", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Produce", active: true, checked: false, notes: "more firm the better; if super soft don't buy" },
  { name: "Mustard", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Horizon Growing Years - Jackson's Milk", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: false },
  { name: "Ground Cinnamon Seasoning (Organic)", primaryStore: "Walmart", category: "Seasonings & Spices", active: true, checked: false },
  { name: "McCormick Thick and Zesty Spaghetti seasoning", primaryStore: "Walmart", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Medela Breastmilk Bags 100 count", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false },
  { name: "Baby D Drops (Organic Vitamin D)", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false },
  { name: "Ziploc Sandwich bags (2 boxes)", primaryStore: "Walmart", secondaryStore: "Sam's Club", category: "Household", active: true, checked: false },
  { name: "Dr Brown straw bottle", primaryStore: "Walmart", category: "Baby & Kids", active: false, checked: false, notes: "the ones Jackson used to have" },
  { name: "Pampers Swaddlers Size 8", primaryStore: "Walmart", secondaryStore: "Sam's Club", category: "Baby & Kids", active: true, checked: false },
  { name: "Small Trash Bags", primaryStore: "Walmart", category: "Household", active: true, checked: false },
  { name: "Philips Avent Soothie pacifiers 2 pack", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false, notes: "for 6 month if they have" },
  { name: "Water Wipes (1 box)", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false },
  { name: "Organic chili powder seasoning", primaryStore: "Walmart", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Diaper Genie replacements", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false },
  { name: "Ground Meat - Jackson's", primaryStore: "Walmart", category: "Meat & Seafood", active: true, checked: false, notes: "check date; buy 85/15 if they have" },
  { name: "Manila envelopes", primaryStore: "Walmart", category: "Household", active: false, checked: false },
  { name: "Organic Black Pepper", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Mission Tortillas Fajita Size (4 packs)", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Bread & Bakery", active: true, checked: false },
  { name: "Great Value Vinyl Disposable gloves", primaryStore: "Walmart", category: "Household", active: true, checked: false },
  { name: "Slap Ya Mamma seasoning", primaryStore: "Walmart", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Dapple Baby Dish Soap", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: false },
  { name: "Fritos Regular (4 bags)", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Snacks", active: true, checked: false },
  { name: "Fritos Scoop Family Size", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Snacks", active: true, checked: false },
  { name: "Ground Cumin seasoning (Organic)", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Rotel cans mild or original", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Hamburger buns", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Bread & Bakery", active: true, checked: false, notes: "check date" },
  { name: "Chips for burger (your choice)", primaryStore: "Walmart", category: "Snacks", active: true, checked: false, notes: "NO CHIPS for Sarah" },
  { name: "Pillow cases 1 pack/2 cases standard size", primaryStore: "Walmart", category: "Household", active: false, checked: false, notes: "tan or navy color" },
  { name: "Birch Benders Buttermilk Pancake Mix (2 bags)", primaryStore: "Walmart", category: "Pantry", active: true, checked: false },
  { name: "Barilla Lasagne Noodles (1 box)", primaryStore: "Walmart", category: "Pantry", active: true, checked: false },
  { name: "Bananas green/organic (6-7)", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Produce", active: true, checked: true },
  { name: "Once Upon a Farm Fruit Packs (2 boxes)", primaryStore: "Walmart", secondaryStore: "Costco", category: "Baby & Kids", active: true, checked: true },
  { name: "Goodnites XS 44 Count", primaryStore: "Walmart", category: "Baby & Kids", active: true, checked: true },
  { name: "Horizon Grassfed Whole Milk", primaryStore: "Walmart", secondaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: true },
  { name: "Distilled water (2 gallons)", primaryStore: "Walmart", category: "Beverages", active: true, checked: true },
  { name: "La Banderita Organic Tortillas Fajita Size", primaryStore: "Walmart", category: "Bread & Bakery", active: true, checked: true, notes: "ONLY IF MAY Exp date" },
  { name: "Organic Cabbage small head", primaryStore: "Walmart", category: "Produce", active: true, checked: true },

  // Kroger
  { name: "Four Sisters White Rice", primaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Four Sisters Wheat Rice", primaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Keebler Whole Grain Crackers", primaryStore: "Kroger", category: "Snacks", active: true, checked: false },
  { name: "Jalapeños", primaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Almond Milk", primaryStore: "Kroger", category: "Beverages", active: true, checked: false },
  { name: "Chicken Breast", primaryStore: "Kroger", category: "Meat & Seafood", active: true, checked: false },
  { name: "Kettle and Fire Beef Broth 32oz", primaryStore: "Kroger", category: "Pantry", active: true, checked: false, notes: "red packaging" },
  { name: "Bunch of carrots", primaryStore: "Kroger", category: "Produce", active: true, checked: false, notes: "if 1 make it large, if 2 make them smaller" },
  { name: "Red Potatoes", primaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Strawberry Jelly (1 jar)", primaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Prunes Sunsweet brand", primaryStore: "Kroger", category: "Pantry", active: true, checked: false, notes: "preservative free" },
  { name: "Hamburger buns 1 pack medium", primaryStore: "Kroger", category: "Bread & Bakery", active: true, checked: false, notes: "your choice check date" },
  { name: "Yogurt for Livvy (1 pack)", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: false, notes: "something fruity" },
  { name: "Ezekiel Bread (1 pack)", primaryStore: "Kroger", category: "Bread & Bakery", active: true, checked: false },
  { name: "Black beans Organic (1 pack/4 cans)", primaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Wheat Germ (1 jar)", primaryStore: "Kroger", category: "Pantry", active: true, checked: false, notes: "aisle 5" },
  { name: "Organic quick oats (1 bag)", primaryStore: "Kroger", category: "Pantry", active: true, checked: false, notes: "for meatloaf" },
  { name: "Organic parsley small container", primaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Dark Red Kidney Beans Organic (4 pack)", primaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Pinto Beans Organic (4 pack)", primaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Organic cottage cheese 8oz", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: false, notes: "4% milk fat or whole milk, check exp date; if no organic get regular" },
  { name: "Vital Farms Organic Pasture Raised Eggs (3 dozen)", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: false },
  { name: "Simply Organic Taco Seasoning Southwest Taco (5+)", primaryStore: "Kroger", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Sargento sharp/Mild shredded cheese", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: false },
  { name: "Sweet potato medium", primaryStore: "Kroger", category: "Produce", active: true, checked: false, notes: "check for worm holes" },
  { name: "Simple Truth Mozzarella Shredded Cheese (2 bags)", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: false, notes: "2 if Sargento brand" },
  { name: "Sargento Creamery Cheddar Slices", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: false },
  { name: "Santa Cruz Creamy peanut butter (1 jar)", primaryStore: "Kroger", category: "Pantry", active: true, checked: false },
  { name: "Large Bell pepper", primaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Large Onion", primaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Garlic Cloves 3 pack", primaryStore: "Kroger", category: "Produce", active: true, checked: false },
  { name: "Micah's Frozen Bread (Kroger only)", primaryStore: "Kroger", category: "Bread & Bakery", active: true, checked: true },
  { name: "Yogurt for Jackson (1 box BANILLA)", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: true, notes: "Banilla, strawberry/Beet, or Pear/Mango/Spinach; CHECK DATES" },
  { name: "Simple Truth Mexican Style Cheese (2 bags)", primaryStore: "Kroger", category: "Dairy & Eggs", active: true, checked: true },
  { name: "Pumice stone (2)", primaryStore: "Kroger", category: "Health & Personal Care", active: true, checked: true },

  // Albertsons
  { name: "Redmond sea salt", primaryStore: "Albertsons", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Organics Ground French Roast Coffee", primaryStore: "Albertsons", category: "Beverages", active: true, checked: false },
  { name: "Organics Ground Decaf French Roast Coffee", primaryStore: "Albertsons", category: "Beverages", active: true, checked: false },
  { name: "Organics Dark Brown Sugar", primaryStore: "Albertsons", category: "Pantry", active: true, checked: false },
  { name: "Organics PANKO Bread Crumbs (2-3 containers)", primaryStore: "Albertsons", category: "Pantry", active: true, checked: false },

  // Sam's Club
  { name: "Plates both sizes", primaryStore: "Sam's Club", category: "Household", active: true, checked: false },
  { name: "Ziploc Storage Gallon bags", primaryStore: "Sam's Club", category: "Household", active: true, checked: false },
  { name: "Charmin Toilet Paper", primaryStore: "Sam's Club", category: "Household", active: true, checked: false },
  { name: "Essentia Water (1 box)", primaryStore: "Sam's Club", category: "Beverages", active: true, checked: false },
  { name: "Ozarka Water (1 box)", primaryStore: "Sam's Club", category: "Beverages", active: true, checked: true },
  { name: "Ziploc Sandwich bags (1 box)", primaryStore: "Sam's Club", category: "Household", active: true, checked: true },
  { name: "Paper Towels (1 pack)", primaryStore: "Sam's Club", category: "Household", active: true, checked: true },
  { name: "Huggies Sensitive Wipes (2 boxes)", primaryStore: "Sam's Club", category: "Baby & Kids", active: true, checked: true },
  { name: "Pampers Swaddlers Size 6", primaryStore: "Sam's Club", category: "Baby & Kids", active: true, checked: true },
  { name: "Pampers Swaddlers Size 5", primaryStore: "Sam's Club", category: "Baby & Kids", active: true, checked: true },
  { name: "Salt Bags", primaryStore: "Sam's Club", category: "Pantry", active: false, checked: true },

  // Costco
  { name: "Once Upon a Farm (check, NO IMMUNITY BLEND)", primaryStore: "Costco", category: "Baby & Kids", active: false, checked: false },
  { name: "Regular Veggies", primaryStore: "Costco", category: "Produce", active: false, checked: false },
  { name: "AA Batteries (1 pack)", primaryStore: "Costco", category: "Household", active: false, checked: false },
  { name: "AAA Batteries (1 pack)", primaryStore: "Costco", category: "Household", active: false, checked: false },
  { name: "9V Batteries", primaryStore: "Costco", category: "Household", active: true, checked: false },
  { name: "Pancake mix", primaryStore: "Costco", category: "Pantry", active: false, checked: false },
  { name: "Water", primaryStore: "Costco", category: "Beverages", active: false, checked: false },
  { name: "Collagen", primaryStore: "Costco", category: "Health & Personal Care", active: false, checked: false },
  { name: "Damp Rid (boxes)", primaryStore: "Costco", category: "Household", active: true, checked: false },
  { name: "Ziploc Regular quart", primaryStore: "Costco", category: "Household", active: true, checked: false },
  { name: "Organic Peet's Ground Coffee (2 bags)", primaryStore: "Costco", category: "Beverages", active: true, checked: false },
  { name: "Oatmeal", primaryStore: "Costco", category: "Pantry", active: true, checked: false },
  { name: "Parchment paper", primaryStore: "Costco", category: "Household", active: true, checked: false },
  { name: "Olive oil (1 bottle)", primaryStore: "Costco", category: "Pantry", active: false, checked: false, notes: "for your dad, single origin from Italy" },
  { name: "Kitchen trash bags", primaryStore: "Costco", category: "Household", active: true, checked: false },
  { name: "Ziploc freezer gallon", primaryStore: "Costco", category: "Household", active: true, checked: false },
  { name: "Avocado oil (1 each)", primaryStore: "Costco", category: "Pantry", active: true, checked: false },
  { name: "Clear Care", primaryStore: "Costco", category: "Health & Personal Care", active: true, checked: false },
  { name: "Tomato sauce", primaryStore: "Costco", category: "Pantry", active: true, checked: false },
  { name: "Tomato Paste (check date)", primaryStore: "Costco", category: "Pantry", active: true, checked: false },
  { name: "Diced Tomato", primaryStore: "Costco", category: "Pantry", active: true, checked: false },
  { name: "Bearded Brothers Bars (1 box)", primaryStore: "Costco", category: "Snacks", active: true, checked: false },
  { name: "Frozen food options for Jackson", primaryStore: "Costco", category: "Frozen", active: false, checked: false, notes: "call me, take pics" },
  { name: "Sauerkraut (2 containers)", primaryStore: "Costco", category: "Pantry", active: true, checked: true, notes: "must stay UPRIGHT in ice chest" },
  { name: "Butter (3 boxes, check exp date)", primaryStore: "Costco", category: "Dairy & Eggs", active: true, checked: true },
  { name: "Chips preference", primaryStore: "Costco", category: "Snacks", active: true, checked: true },
  { name: "Gain detergent", primaryStore: "Costco", category: "Household", active: true, checked: true },
  { name: "Lunch meat (1-2 packs)", primaryStore: "Costco", category: "Meat & Seafood", active: true, checked: true },
  { name: "Frozen 100% grass fed burger patties (2 packs)", primaryStore: "Costco", category: "Frozen", active: true, checked: true },
  { name: "Wild Caught Salmon (1 bag)", primaryStore: "Costco", category: "Meat & Seafood", active: true, checked: true },
  { name: "Chicken nuggets (4 bags)", primaryStore: "Costco", category: "Frozen", active: true, checked: true },
  { name: "Frozen Broccoli Florets (1 bag)", primaryStore: "Costco", category: "Frozen", active: true, checked: true },
  { name: "Snack Bars Jackson", primaryStore: "Costco", category: "Snacks", active: true, checked: true, notes: "call me, take pics" },
  { name: "Peanut butter (2 packs, check date)", primaryStore: "Costco", category: "Pantry", active: true, checked: true },
  { name: "Jelly (7 jars)", primaryStore: "Costco", category: "Pantry", active: true, checked: true },
  { name: "Aussie Bites (4 packs, depends on date)", primaryStore: "Costco", category: "Snacks", active: true, checked: true },

  // Whole Foods
  { name: "Yogurt", primaryStore: "Whole Foods", category: "Dairy & Eggs", active: false, checked: false },
  { name: "Baja Gold salt", primaryStore: "Whole Foods", category: "Seasonings & Spices", active: true, checked: false },
  { name: "Deodorant", primaryStore: "Whole Foods", category: "Health & Personal Care", active: true, checked: false },
  { name: "Coffee", primaryStore: "Whole Foods", category: "Beverages", active: false, checked: false },
  { name: "Pears", primaryStore: "Whole Foods", category: "Produce", active: true, checked: false },
  { name: "Onions", primaryStore: "Whole Foods", category: "Produce", active: true, checked: false },
  { name: "Sweet Potato", primaryStore: "Whole Foods", category: "Produce", active: true, checked: false },
  { name: "Zinc - Jackson", primaryStore: "Whole Foods", category: "Health & Personal Care", active: true, checked: false },
  { name: "Cookies (singles at register)", primaryStore: "Whole Foods", category: "Snacks", active: true, checked: true, notes: "brown butter or apple butter acceptable" },
  { name: "Vitamin C (1 box)", primaryStore: "Whole Foods", category: "Health & Personal Care", active: true, checked: true },
  { name: "Sarah protein bars", primaryStore: "Whole Foods", category: "Snacks", active: true, checked: true },
  { name: "Micah protein bars", primaryStore: "Whole Foods", category: "Snacks", active: true, checked: true },
  { name: "Eggs (1 pack/18)", primaryStore: "Whole Foods", category: "Dairy & Eggs", active: true, checked: true },
  { name: "Peanut butter large jar Sarah", primaryStore: "Whole Foods", category: "Pantry", active: true, checked: true },
  { name: "Organic Turkey bacon (2-3 packs)", primaryStore: "Whole Foods", category: "Meat & Seafood", active: true, checked: true, notes: "must submerge in ice chest" },
  { name: "Lunch meat (1 pack)", primaryStore: "Whole Foods", category: "Meat & Seafood", active: true, checked: true },
]
